#!/bin/bash



cd ..
#!/bin/bash


curl -fsSL https://ollama.com/install.sh | sh

wget https://pfda-production-static-files.s3.amazonaws.com/cli/pfda-linux-2.7.1.tar.gz

tar -xvzf pfda-linux-2.7.1.tar.gz

rm pfda-linux-2.7.1.tar.gz

python3 -m nltk.downloader all

# Error handling loop.
iteration=0
limit=3
seconds_in_wait=5

while [[ $iteration -le $limit ]];
do


ollama pull llama3.2:1b
ollama pull nomic-embed-text

sudo apt update && sudo apt upgrade -y
sudo apt install -y software-properties-common

sudo apt install -y python3.9 python3.9-venv python3.9-dev

sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 1
sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.9 2
sudo update-alternatives --set python3 /usr/bin/python3.9


git clone https://github.com/SlickbitTechnologies/precisionFDA.git
cd precisionFDA

pip install -r requirements.txt
streamlit run main.py --server.port=8080 &
cd ..

if [[ $? -eq 99 ]]; then
    if [[ $iteration -eq $limit ]]; then
        echo "Maximum times allowed - Error"
        exit 2
    else
        ((iteration++))  # Increment iteration
        sleep "$seconds_in_wait"
    fi
else
    iteration=$((limit + 1))  # Ensure loop exits
fi

done

